name: Trigger auto deployment for applysucksmemory
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build image for specified platform
        run: |
          docker build --platform linux/amd64 \
                        -t applysucksmemory.azurecr.io/applysucksmemory:latest \
                        -f Dockerfile .
      - name: Push image to ACR
        run: |
          az acr login --name applysucksmemory
          docker push applysucksmemory.azurecr.io/applysucksmemory:latest

      - name: Restart Azure Container App revision
        run: |
          az containerapp revision restart \
            --revision applysucksmemory--pncow67 \
            --resource-group applysucksbackendapi